name: Lint

on:
  workflow_call:

jobs:
  lint:
    name: Flake8 Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Install
        run: pip install flake8

      - name: Run
        run: flake8 main.py tests/ --max-line-length=100 --ignore=E302,W503