name: Docker Lint

on:
  workflow_call:

jobs:
  docker-lint:
    name: Hadolint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          failure-threshold: warning